name: Build

on:
  push:
    branches: [ master, 'feature**' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    uses: mbeckh/cmake-utils/.github/workflows/run-build.yml@feature-workflow
    secrets: inherit
